# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GHA::JobBuilder`.
# Please instead update this file by running `bin/tapioca dsl GHA::JobBuilder`.


class GHA::JobBuilder; end
