name: Publish Ruby Gem to GitHub Packages

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Configure gem credentials
        run: |
          mkdir -p ~/.gem
          cat > ~/.gem/credentials << EOF
          ---
          :github: Bearer ${{ secrets.GITHUB_TOKEN }}
          EOF
          chmod 600 ~/.gem/credentials

      - name: Build gem
        run: |
          gem build *.gemspec

      - name: Publish to GitHub Packages
        run: |
          gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
